#pragma once

#define TAP_CODE_DELAY 10

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 3
#define AUTO_MOUSE_TIME 150
#define AUTO_MOUSE_THRESHOLD 500

#define TAPPING_TERM 160
