#pragma once

#define KEYBALL_SCROLLSNAP_ENABLE 0

#define TAP_CODE_DELAY 5

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 1
#define AUTO_MOUSE_TIME 500
#define AUTO_MOUSE_THRESHOLD 100

#define TAPPING_TERM 160
