#pragma once

#define TAP_CODE_DELAY 10

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 1
#define AUTO_MOUSE_TIME 200
#define AUTO_MOUSE_THORESHOLD 100000

#define TAPPING_TERM 160
#define RETRO_TAPPING

